"""add_hashed_password

Revision ID: 294727292b19
Revises: 165ec07ff877
Create Date: 2026-09-20 21:05:50.269072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294727292b19'
down_revision: Union[str, Sequence[str], None] = '165ec07ff877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    
    # 2. Backfill existing users
    op.execute("UPDATE users SET hashed_password = 'temp_hash_please_reset' WHERE hashed_password IS NULL")
    
    # 3. Alter column to NOT NULL
    op.alter_column('users', 'hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
