"""Add review_reasons to ActionItem

Revision ID: 847e23cbf93a
Revises: 294727292b19
Create Date: 2026-09-20 22:17:04.922485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '847e23cbf93a'
down_revision: Union[str, Sequence[str], None] = '294727292b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_items', sa.Column('review_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_items', 'review_reasons')
    # ### end Alembic commands ###
